import Head from 'next/head'
import styles from '../styles/Home.module.css'

import BlogCard from "../components/BlogCard"

import {GraphQLClient, gql} from 'graphql-request'

const graphcms = new GraphQLClient(
  "https://api-ap-southeast-2.graphcms.com/v2/cl46axthy1suq01ywf4ew8bvu/master"
);

const QUERY = gql`
{
  posts {
    title
  }
}
`

// Fetch Request

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          {posts.map((post) => (
            <BlogCard title=
                {post.title} 
                author={post.author} 
                coverPhoto={post.coverPhoto} 
                key={post.id}
                datePublished={post.datePublished}
                slug={post.slug}
                />
          ))}
      </main>
   </div>
  )
}
